{
    "openapi" : "3.0.1",
    "info" : {
        "title" : "Fazendas",
        "description" :"Documnetation from fazendas api",
        "version" : "1.0.0" ,
        "contact":{
            "name": "Sebasti√£o Afonso Domingos",
            "email" : "sebastiaodomingos380@gmail.com"
        }  
    },
    "basePath" : "/",
    "components" : {
        "securitySchemes" : {
            "bearerAuth" : {
                "type" : "http",
                "scheme" : "bearer",
                "bearerFormat" : "JWT",
                "name" : "baererAuth"
            }
        },
        "responses" : {
            "UnauthorizedError":{
                "description": "Access token is missing or invalid"
            }
        }
    },
    "paths" : {
        "/session" : {
            "post" : {
                "tags" : ["Session"],
                "description": "fazer login",
                "summary" : "Rota permite o administrador fazer login",
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "email" : {
                                        "type" : "string"
                                    },
                                    "senha" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "email" : "seba@gmail.com",
                                    "senha" : "1234556"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a administrador"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        }
        ,
        "/administradores" : {
            "post" : {
                "tags" : ["Administrador"],
                "description": "criar administrador",
                "summary" : "Rota que cria a administrador",
                "security":{
                    "bearerAuth" :[]
                },
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    },
                                    "email" : {
                                        "type" : "string"
                                    },
                                    "senha" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"sebastiao",
                                    "email" : "seba@gmail.com",
                                    "senha" : "1234556"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a administrador"
                    },
                    "401" : {
                        "$ref": "#/components/responses/UnauthorizedError"
                    }
               }
            },
            "get" : {
                "tags" : ["Administrador"],
                "descrption" : "listar todas as administradores",
                "summary" : "Rota que lista todas as administradores",
                "security":{
                    "bearerAuth" :[""]
                },
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a administrador"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/administradores/{id}" : {
            "get" : {
                "tags" : ["Administrador"],
                "summary" :"Rota que pega a administrador pelo id",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "name":"id",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao pegar o administrador"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "patch" : {
                "tags" : ["Administrador"],
                "summary" :"Rota que atualiza a administrador",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    },
                                    "email" : {
                                        "type" : "string"
                                    },
                                    "senha" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"sebastiao",
                                    "email" : "seba@gmail.com",
                                    "senha" : "1234556"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a administrador"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "delete" : {
                "tags" : ["Administrador"],
                "summary" :"Rota que elimina a administrador",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "responses" : {
                    "204" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a administrador"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/proprietarios" : {
            "post" : {
                "tags" : ["Proprietarios"],
                "description": "criar proprietario",
                "summary" : "Rota que cria a proprietario",
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    },
                                    "nif" : {
                                        "type" : "string"
                                    },
                                    "distrito" : {
                                        "type": "string"
                                    },
                                    "bairro" : {
                                        "type": "string"
                                    },
                                    "id_municipio" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"sebastiao",
                                    "nif" : "23234DF233",
                                    "distrito" : "Rangel",
                                    "bairro" : "Dona Malha",
                                    "id_municipio" : "werwer-werwer-wewrerw-qweqwe"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a proprietario"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "get" : {
                "tags" : ["Proprietarios"],
                "descrption" : "listar todas as proprietarioes",
                "summary" : "Rota que lista todas as proprietarios",
                "parameters" : [
                    {
                        "in" : "query",
                        "currentPage" : "currentPage",
                        "type" : "number",
                        "name":"currentPage"
                    },
                    {
                        "in" : "query",
                        "perPage" : "perPage",
                        "type" : "number",
                        "name":"perPage"
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a proprietario"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/proprietariosFindByName" : {
            "get" : {
                "tags" : ["Proprietarios"],
                "summary" :"Rota que pega a provincia pelo nome",
                "parameters" : [
                    {
                        "in" : "query",
                        "nome" : "nome",
                        "type" : "string",
                        "name":"nome"
                    },
                    {
                        "in" : "query",
                        "nif" : "nif",
                        "type" : "string",
                        "name":"nif"
                    },
                    {
                        "in" : "query",
                        "bairro" : "bairro",
                        "type" : "string",
                        "name":"bairro"
                    },
                    {
                        "in" : "query",
                        "distrito" : "distrito",
                        "type" : "string",
                        "name":"distrito"
                    },
                    {
                        "in" : "query",
                        "id_municipio" : "id_municipio",
                        "type" : "string",
                        "name":"id_municipio"
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/proprietarios/{id}" : {
            "get" : {
                "tags" : ["Proprietarios"],
                "summary" :"Rota que pega a proprietario pelo id",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "name":"id",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao pegar o proprietario"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "put" : {
                "tags" : ["Proprietarios"],
                "summary" :"Rota que atualiza a proprietario",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "type" : "string"
                                    },
                                    "nif" : {
                                        "type" : "string"
                                    },
                                    "id_municipio" : {
                                        "type": "string"
                                    },
                                    "distrito" : {
                                        "type": "string"
                                    },
                                    "bairro" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"sebastiao",
                                    "nif" : "23234DF233",
                                    "id_municipio" : "werwer-werwer-wewrerw-qweqwe",
                                    "distrito" : "Rangel",
                                    "bairro" : "Dona Malha"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a proprietario"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "delete" : {
                "tags" : ["Proprietarios"],
                "summary" :"Rota que elimina a proprietario",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "responses" : {
                    "204" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a proprietario"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/provincias" : {
            "post" : {
                "tags" : ["Prov√≠ncias"],
                "description": "criar provincia",
                "summary" : "Rota que cria a provincia",
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"Luanda"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "get" : {
                "tags" : ["Prov√≠ncias"],
                "descrption" : "listar todas as provicnias",
                "summary" : "Rota que lista todas as pprovincias",
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/provinciasFindByName" : {
            "get" : {
                "tags" : ["Prov√≠ncias"],
                "summary" :"Rota que pega a provincia pelo nome",
                "parameters" : [{
                    "in" : "query",
                    "nome" : "nome",
                    "type" : "string",
                    "name":"nome",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/provincias/{id}" : {
            "get" : {
                "tags" : ["Prov√≠ncias"],
                "summary" :"Rota que pega a provincia pelo id",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "name":"id",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "put" : {
                "tags" : ["Prov√≠ncias"],
                "summary" :"Rota que atualiza a provincia",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    }
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "delete" : {
                "tags" : ["Prov√≠ncias"],
                "summary" :"Rota que elimina a provincia",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "responses" : {
                    "204" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/municipios" : {
            "post" : {
                "tags" : ["Munic√≠pios"],
                "description": "criar municipio",
                "summary" : "Rota que cria a municipio",
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    },
                                    "id_provincia" : {
                                        "type" : "string"
                                    }
                                },
                                "example" : {
                                    "nome" :"Luanda",
                                    "id_provincia" : "fdfgdfd-dfgdf-dfgdfg-dfgdf4"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "get" : {
                "tags" : ["Munic√≠pios"],
                "descrption" : "listar todas as provicnias",
                "summary" : "Rota que lista todas as pprovincias",
                "parameters" : [
                    {
                        "in" : "query",
                        "id" : "id",
                        "name" : "id",
                        "type" : "string"
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/municipiosFindByName" : {
            "get" : {
                "tags" : ["Munic√≠pios"],
                "summary" :"Rota que pega a municipio pelo nome",
                "parameters" : [{
                    "in" : "query",
                    "nome" : "nome",
                    "type" : "string",
                    "name":"nome",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/municipios/{id}" : {
            "get" : {
                "tags" : ["Munic√≠pios"],
                "summary" :"Rota que pega a municipio pelo id",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "name":"id",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao pegar o municipio"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "patch" : {
                "tags" : ["Munic√≠pios"],
                "summary" :"Rota que atualiza a municipio",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "nome" : {
                                        "typ" : "string"
                                    },
                                    "id_provincia" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "nome" : "Luanda",
                                    "id_provincia" : "fdfgdfd-dfgdf-dfgdfg-dfgdf4"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "delete" : {
                "tags" : ["Munic√≠pios"],
                "summary" :"Rota que elimina a provincia",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "responses" : {
                    "204" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a provincia"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/fazendas" : {
            "post" : {
                "tags" : ["Fazendas"],
                "description": "criar fazenda",
                "summary" : "Rota que cria a fazenda",
               "requestBody" : {
                    "content" : {
                        "multipart/form-data" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "id_proprietario" : {
                                        "type": "string",
                                        "required" : true
                                    },
                                    "codigo" : {
                                        "type" : "string",
                                        "required" : true
                                    },
                                    "nome" : {
                                        "type" : "string",
                                        "required" : true
                                    },
                                    "imagens" : {
                                        "type": "file" ,
                                        "required" : true
                                    },
                                    "id_municipio" : {
                                        "type": "string",
                                        "required" : true
                                    },
                                    "distrito" : {
                                        "type": "string",
                                        "required" : true
                                    },
                                    "bairro" : {
                                        "type": "string",
                                        "required" : true
                                    }
                                   
                                },
                                "example" : {
                                    "id_proprietario" : "werwer-werwer-wewrerw-qweqwe",
                                    "codigo" :"FAZ-01212",
                                    "nome" :"FazCastro",
                                    "foto" : "http://localhost:343",
                                    "id_municipio" : "werwer-werwer-wewrerw-qweqwe",
                                    "distrito" : "Rangel",
                                    "bairro" : "Dona Malha"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "get" : {
                "tags" : ["Fazendas"],
                "descrption" : "listar todas as fazendas",
                "summary" : "Rota que lista todas as fazendas",
                "parameters" : [
                    {
                        "in" : "query",
                        "distrito" : "distrito",
                        "type" : "string",
                        "name":"distrito"
                    },
                    {
                        "in" : "query",
                        "bairro" : "bairro",
                        "type" : "string",
                        "name":"bairro"
                    },
                    {
                        "in" : "query",
                        "id_municipio" : "id_municipio",
                        "type" : "string",
                        "name":"id_municipio"
                    },
                    {
                        "in" : "query",
                        "id_proprietario" : "id_proprietario",
                        "type" : "string",
                        "name":"id_proprietario"
                    },
                    {
                        "in" : "query",
                        "currentPage" : "currentPage",
                        "type" : "number",
                        "name":"currentPage"
                    },
                    {
                        "in" : "query",
                        "perPage" : "perPage",
                        "type" : "number",
                        "name":"perPage"
                    }
                ],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao criar a fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/fazendas/{id}" : {
            "get" : {
                "tags" : ["Fazendas"],
                "summary" :"Rota que pega a fazenda pelo id",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "name":"id",
                    "required" : true
                }],
                "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao pegar o fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            },
            "delete" : {
                "tags" : ["Fazendas"],
                "summary" :"Rota que elimina a fazenda",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "responses" : {
                    "204" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao eliminar a fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/fazendas/dados/{id}" :{
            "put" : {
                "tags" : ["Fazendas"],
                "description" : "Rota que atualiza os dados da fazenda",
                "summary" :"Rota que atualiza os dados da fazenda",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "application/json" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "id_proprietario" : {
                                        "type": "string"
                                    },
                                    "codigo" : {
                                        "type" : "string"
                                    },
                                    "nome" : {
                                        "type" : "string"
                                    },
                                    "id_municipio" : {
                                        "type": "string"
                                    },
                                    "distrito" : {
                                        "type": "string"
                                    },
                                    "bairro" : {
                                        "type": "string"
                                    }
                                },
                                "example" : {
                                    "id_proprietario" : "werwer-werwer-wewrerw-qweqwe",
                                    "codigo" :"FAZ-01212",
                                    "nome" :"FazCastro",
                                    "id_municipio" : "werwer-werwer-wewrerw-qweqwe",
                                    "distrito" : "Rangel",
                                    "bairro" : "Dona Malha"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao atualizar a fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        },
        "/fazendas/imagem/{id}" :{
            "put" : {
                "tags" : ["Fazendas"],
                "description" : "Rota que atualiza as imagens da fazenda",
                "summary" :"Rota que atualiza as imagens da fazenda",
                "parameters" : [{
                    "in" : "path",
                    "id" : "id",
                    "type" : "string",
                    "required" : true,
                    "name" : "id"
                }],
               "requestBody" : {
                    "content" : {
                        "multipart/form-data" : {
                            "schema" : {
                                "type" : "object",
                                "properties" : {
                                    "imagem" : {
                                        "type" : "file"
                                    }
                                },
                                "example" : {
                                    "id_proprietario" : "werwer-werwer-wewrerw-qweqwe",
                                    "codigo" :"FAZ-01212",
                                    "nome" :"FazCastro",
                                    "id_municipio" : "werwer-werwer-wewrerw-qweqwe",
                                    "distrito" : "Rangel",
                                    "bairro" : "Dona Malha"
                                }
                            }
                        }
                    }
               },
               "responses" : {
                    "200" : {
                        "description" : "okay"
                    },
                    "400" : {
                        "description" : "Erro ao atualizar a fazenda"
                    },
                    "401" : {
                        "description" : "Unauthorized"
                    }
               }
            }
        }
    }
}